"""add skills column to candidates for candidate profile

Revision ID: 1cf3d162c7d0
Revises: 23e23214b62e
Create Date: 2026-08-17 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1cf3d162c7d0'
down_revision: Union[str, None] = '23e23214b62e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'candidates',
        sa.Column('skills', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'skills')
    # ### end Alembic commands ###
