"""add skill_analysis jsonb column to resumes for skill engine output

Revision ID: 59de596cadd1
Revises: f13ca66255c9
Create Date: 2026-09-03 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '59de596cadd1'
down_revision: Union[str, None] = 'f13ca66255c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'resumes',
        sa.Column('skill_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'skill_analysis')
    # ### end Alembic commands ###
