"""add matching-score fields to jobs and candidates

Revision ID: 6ce9f65543bc
Revises: 59de596cadd1
Create Date: 2026-09-10 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce9f65543bc'
down_revision: Union[str, None] = '59de596cadd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('required_seniority', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('required_education', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'location')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'required_education')
    op.drop_column('jobs', 'required_seniority')
    # ### end Alembic commands ###
