"""add fields to jobs table for job service

Revision ID: 8dd76205f78e
Revises: de4c677d0be4
Create Date: 2026-08-12 10:55:26.980349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dd76205f78e'
down_revision: Union[str, None] = 'de4c677d0be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('jobs', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('skills_required', postgresql.ARRAY(sa.String(length=100)), nullable=True))
    op.add_column('jobs', sa.Column('salary_range', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('jobs', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'jobs', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.alter_column('jobs', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'salary_range')
    op.drop_column('jobs', 'skills_required')
    op.drop_column('jobs', 'department')
    op.drop_column('jobs', 'created_by')
    # ### end Alembic commands ###
