"""add parsed_data jsonb column to resumes for NER pipeline output

Revision ID: f13ca66255c9
Revises: 1cf3d162c7d0
Create Date: 2026-08-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f13ca66255c9'
down_revision: Union[str, None] = '1cf3d162c7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'resumes',
        sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'parsed_data')
    # ### end Alembic commands ###
