"""fix scheduled_at timezone and add reminder_job_ids to interviews

Revision ID: fd3a06ef991c
Revises: 6ce9f65543bc
Create Date: 2026-09-17 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fd3a06ef991c'
down_revision: Union[str, None] = '6ce9f65543bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'interviews',
        'scheduled_at',
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.add_column(
        'interviews',
        sa.Column('reminder_job_ids', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'reminder_job_ids')
    op.alter_column(
        'interviews',
        'scheduled_at',
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
